services:
  mysql:
    image: mysql:8.0
    container_name: cs2-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: api
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_pwd"]
      interval: 10s
      timeout: 5s
      retries: 5
